# Generated by Django 4.1.6 on 2023-04-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('complaint', models.TextField()),
                ('complaintDate', models.DateTimeField()),
            ],
        ),
    ]
