# Generated by Django 4.1.6 on 2023-04-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozumburada', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
