# Generated by Django 4.1.6 on 2023-04-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozumburada', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
