# Generated by Django 4.1.6 on 2023-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozumburada', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
    ]
