# Generated by Django 4.1.6 on 2023-05-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cozumburada', '0015_complaint_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintDate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('complaint', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cozumburada.complaint')),
            ],
        ),
    ]
