# Generated by Django 4.1.6 on 2023-04-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozumburada', '0016_image_remove_complaint_images_alter_complaint_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='images',
            field=models.ManyToManyField(blank=True, to='cozumburada.image'),
        ),
    ]
