# Generated by Django 4.1.6 on 2023-05-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cozumburada', '0017_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
